# Generated by Django 5.2.7 on 2025-10-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.CharField(default='100g', max_length=10),
        ),
    ]
