# Generated by Django 5.2.7 on 2025-10-24 13:51

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactform_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_variant',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('100g', '100g'), ('200g', '200g'), ('500g', '500g'), ('1kg', '1kg'), ('2kg', '2kg'), ('5kg', '5kg')], max_length=50),
        ),
    ]
