# Generated by Django 5.2.7 on 2025-10-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_orderhistory_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='total_amount',
            new_name='bill_amount',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='variant',
            field=models.CharField(default='100g', max_length=10),
        ),
    ]
