# Generated by Django 5.2.7 on 2025-10-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_variant',
            field=models.CharField(choices=[('100g', '100g'), ('200g', '200g'), ('500g', '500g'), ('1kg', '1kg'), ('2kg', '2kg'), ('5kg', '5kg')], max_length=10),
        ),
    ]
