# Generated by Django 5.2.7 on 2025-10-24 14:51

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_mrp',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_variant',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('100g', '100g'), ('200g', '200g'), ('500g', '500g'), ('1kg', '1kg'), ('2kg', '2kg'), ('5kg', '5kg')], max_length=26),
        ),
    ]
