# Generated by Django 5.2.7 on 2025-10-26 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_product_price_data_alter_product_product_mrp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_lane1',
            new_name='user_mail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_landmark',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_pincode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_state',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_lane1', models.CharField(max_length=100)),
                ('address_landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('address_city', models.CharField(max_length=25)),
                ('address_district', models.CharField(max_length=25)),
                ('address_state', models.CharField(max_length=25)),
                ('address_pincode', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
